services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: savings
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    network_mode: host

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    network_mode: host

  frontend:
    build:
      context: ./frontend/apps/web
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - backend
    env_file:
      - ./frontend/apps/web/.env

volumes:
  pgdata:
